In [1]:
import numpy as np
import pandas as pd
import os

In [2]:
#Read file related to testing
def get_test_file():
    '''Generator that return string of file name'''
    import re
    for files in os.listdir():
        if re.match('test.+\.csv', files) is not None:
            yield files
            
def csv_to_np(filename):
    return pd.read_csv(filename, header=None, delim_whitespace=True).values
    

In [3]:
for filename in get_test_file():
    input_test = csv_to_np(filename)
    print(input_test)

[[ 0  0  0  0  0  0  0  0  0 13  0  9 13  0  0  0 12  3  3  0]
 [ 0  0  8 13  9  0  0  0  0  0  3  2  0  0  4 13  9  6  8  2]
 [ 0  8  0  0  7  9  0  0  0  0  1  0  9 13  0  0 10  1  0  0]
 [ 0 13  0  0  0 15 13 16 10  0  0  0  1  0  0 12  0  6  0  0]
 [ 0  9  7  0  0  0  3  0 12  0  0  0  0  0 16  9  0  2  2  0]
 [ 0  0  9 15  0  0  8 14  0  0  0 15  0  9  2  3  5  0  0  7]
 [ 0  0  0 13  3  8  0 10 13 11  0  7 14  2  0  0  0 11  0  3]
 [ 0  0  0 16  0 14 10  0  0  9  0  6  0 12  6  5 15  0  0  0]
 [ 0  0  0 10 12  0 13  0  0  4  6  0  6  5  0  0 11  0  9  0]
 [13  0  0  0  0  0 11  9  4  0  0 11  0  0  2  2  0  8  1 13]
 [ 0  3  1  0  0  0  0  0  6  0  0  0  0  1 10 12  0  0  0  0]
 [ 9  2  0  0  0 15  7  6  0 11  0  0 11  1  7  0  5  0  0  0]
 [13  0  9  1  0  0 14  0  6  0  0 11  0  3  0 14  0  0  0  6]
 [ 0  0 13  0  0  9  2 12  5  1  1  1  3  0  0  0  0  0 12 10]
 [ 0  4  0  0 16  2  0  6  0  2 10  7  0  0  0  5  1  0  7  0]
 [ 0 13  0 12  9  3  0  5  0  2 12  0 14  0  5  0  7  0